server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/globalgates?serverTimezone=Asia/Seoul
    username: globalgates
    password: 1234
  session:
    redis:
      repository-type: indexed
      flush-mode: immediate
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  profiles:
    active: local
    include: oauth

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 5MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.app.globalgates.domain; com.app.globalgates.dto;
  type-handlers-package: com.app.globalgates.mybatis.handler
  configuration:
    map-underscore-to-camel-case: true

# openssl rand -base64 32
jwt:
  secret: D/XhOi75i22MG5x3JJ0Cq93pa4WOLPwCbdYFWcEBCdI=

aws:
  access-key: 123
  secret-key: 1234
  s3:
    bucket-name: bucket-gb-hds
  region: ap-northeast-2